# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
#pod 'JSONKit',
#pod 'ASIHTTPRequest'

platform :ios
pod 'AFNetworking'
pod 'Baidu-Maps-iOS-SDK', '~> 2.2.1'


# Uncomment this line if you're using Swift
# use_frameworks!

target 'MyOCApp' do

end

target 'MyOCAppTests' do

end

